### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true # automatically start the local network container, if not already running

[[development.accounts]]
name = "nick" # Required. Keys for this account will be saved to `./.stellar/identity`
default = true # Optional. Whether to use this account as the `--source` for commands that need one.

[development.contracts.hello_world]
# Generate a contract client (NPM package) for this contract. This means:
#   - compile (build) the contract source to Wasm
#   - deploy the contract to the `network` specified above
#   - generate an NPM client (also called the "TS Bindings") for the deployed
#     contract to the NPM workspace in `packages/*`
#   - import the contract for easy access in the frontend in `src/contracts`
client = true

# If your contract has a `__constructor`, specify your arguments to it here.
# Only available in `development` and `testing` environments
#constructor_args = """
--owner GDY5WPUFRR5ZCJVA3T56S2YSHZPU7EXP4ACT7AJVCH625HB24EJMJIRU --symbol "POA" --uri "www.mytoken.com" --name "Event 1"
"""

# Coming Soon: Specify live contracts to bind & import in this project using the given name.
# During initialization, these contracts will also be "spooned" into the development network,
# meaning that their data will match the live network at the given sequence number.
# [development.contracts.eurc]
# environment = "production"
# address = "C..."
# at-ledger-sequence = 50153603

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]
# hello_world = { id = "C123..." }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# hello_world = { id = "C987..." }
